FROM node:18-alpine AS builder

WORKDIR /app/react

COPY ./react/package*.json ./

RUN npm install

COPY ./react .

RUN npm run build

# Production runtime
FROM nginx:alpine AS production

COPY --from=builder /app/react/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173

CMD ["nginx", "-g", "daemon off;"]