name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Added for better build performance

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Updated to v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: puneetnj/express_react_be:latest
          cache-from: type=registry,ref=puneetnj/express_react_be:latest
          cache-to: type=inline

      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          file: ./Dockerfile.react
          push: true
          tags: puneetnj/express_react_fe:latest
          cache-from: type=registry,ref=puneetnj/express_react_fe:latest
          cache-to: type=inline

      - name: Verify Backend Image
        run: |
          docker pull puneetnj/express_react_be:latest
          docker image inspect puneetnj/express_react_be:latest

      - name: Verify Frontend Image
        run: |
          docker pull puneetnj/express_react_fe:latest
          docker image inspect puneetnj/express_react_fe:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull puneetnj/express_react_be:latest
            sudo docker stop express_react_be || true
            sudo docker rm express_react_be || true
            sudo docker run -d --name express_react_be -p 3500:3500 puneetnj/express_react_be:latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Pull and Extract Frontend Assets
        run: |
          docker pull puneetnj/express_react_fe:latest
          docker create --name temp_container puneetnj/express_react_fe:latest
          docker cp temp_container:/usr/share/nginx/html/. ./dist
          docker rm temp_container

      - name: Deploy to S3
        run: |
          aws s3 sync dist s3://${{ secrets.S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
