name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Added for better build performance

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Updated to v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Docker image
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: puneetnj/express_react_be:latest
          cache-from: type=registry,ref=puneetnj/express_react_be:latest
          cache-to: type=inline

      - name: Build and Push Frontend Docker image
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          file: ./Dockerfile.react
          push: true
          tags: puneetnj/express_react_fe:latest
          cache-from: type=registry,ref=puneetnj/express_react_fe:latest
          cache-to: type=inline

      - name: Verify Backend Image
        run: |
          docker pull puneetnj/express_react_be:latest
          docker image inspect puneetnj/express_react_be:latest

      - name: Verify Frontend Image
        run: |
          docker pull puneetnj/express_react_fe:latest
          docker image inspect puneetnj/express_react_fe:latest
